PROJ=microhttpserver

CC=cc
#TARGET=arm-linux-gnueabihf-
#TOOLPATH=/home/zack/rpi/tools/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/bin/$(TARGET)
#CC=$(TOOLPATH)gcc
#OBJCOPY=$(TOOLPATH)objcopy
#OBJDUMP=$(TOOLPATH)objdump
INCLUDES=-I.
CFLAGS=$(INCLUDES) -Os -D_PARSE_SIGNAL_ -D_PARSE_SIGNAL_INT_ -DDEBUG_MSG --static
SRCS=main.c server.c middleware.c

all:
	$(CC) $(SRCS) $(CFLAGS) -o $(PROJ)
	#$(OBJCOPY) $(PROJ) -O binary kernel.img
	#$(OBJDUMP) -d $(PROJ) > $(PROJ).list

clean:
	rm -rf *.out *.bin *.exe *.o *.a *.so *.list *.img test build $(PROJ)
